apiVersion: v1
kind: ConfigMap
metadata:
  name: kia-billing-config
data:
  node: "development"
  port: "8002"
  database_uri: "mongodb://<USERNAME>:<PASSWORD>@mngdb:27017/hatters"
  kafka_url: "cp-cp-kafka.broker.svc.cluster.local:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: kia-billing-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5wYXNzdzByZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kia-email-config
data:
  node: "development"
  port: "8003"
  mailtrap-host: "smtp.mailtrap.io"
  mailtrap-port: "2525"
  mailtrap-from: "santiago@gmail.com"
  sendgrip-from: "mozgolom92@mail.ru"
  user_url: "http://kia-user-service.auth.svc.cluster.local:9001"
  kafka_url: "cp-cp-kafka.broker.svc.cluster.local:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: kia-email-secret
type: Opaque
data:
  mailtrap-username: ZjdhOGFhNDczODY2Yjg=
  mailtrap-password: ODFkN2U0Y2ViZGE5NTg=
  sendgrip-username: YXBpa2V5
  sendgrip-password: U0cuMFFMRTY2eVFUZ090eVNwcXZCTzdWQS5Beno4dFZhODdKeWtzT0Y5ZGpKcFNjN080V0UzWjR0WTBVS0VZVk5zSXZz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kia-order-config
data:
  node: "development"
  port: "8004"
  database_uri: "mongodb://<USERNAME>:<PASSWORD>@mngdb:27017/hatters"
  kafka_url: "cp-cp-kafka.broker.svc.cluster.local:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: kia-order-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5wYXNzdzByZA==