apiVersion: v1
kind: ConfigMap
metadata:
  name: kia-config
data:
  node: "development"
  database_uri: "mongodb://<USERNAME>:<PASSWORD>@mngdb:27017/hatters"
---
apiVersion: v1
kind: Secret
metadata:
  name: kia-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5wYXNzdzByZA==