apiVersion: apps/v1
kind: Deployment
metadata:
  name: kia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kia-hw2
  template:
    metadata:
      labels:
        app: kia-hw2
    spec:
      containers:
        - name: kia-otus-arch
          image: ilyakozyrev/kia-otus-arch:hw2
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: kia-config
                  key: node
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kia-config
                  key: database_uri
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kia-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kia-secret
                  key: password
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5