{
 "title": "hw3",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Latency (0.5 Quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (path, le) (rate(responses_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency (0.95 Quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, le) (rate(responses_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency (0.99 Quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (path, le) (rate(responses_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency (max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (path, le) (rate(responses_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency Ingress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(pathsTaken[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "RPS Ingress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path,method) (rate(responses_count{status=\"500\"}[1m]))",
     "legendFormat": "{{path,method}}"
    }
   ]
  },
  {
   "title": "Error Rate Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests{status=~\"5.+\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"myapp\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"myapp\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}