apiVersion: v1
kind: Service
metadata:
  name: kia-order-service
  labels:
    app: kia-order-hw5
spec:
  selector:
    app: kia-order-hw5
  ports:
    - protocol: TCP
      port: 9004
      targetPort: order-web
  type: NodePort