apiVersion: v1
kind: ConfigMap
metadata:
  name: kia-config
data:
  host: "0.0.0.0"
  port: "8000"
  node_env: "development"
  database_uri: {{ printf "mongodb://<USERNAME>:<PASSWORD>@%s:%s/%s" (include "mongodb.fullname" .) .Values.mongodb.service.port .Values.mongodb.auth.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kia-secret
type: Opaque
data:
  username: {{ printf .Values.mongodb.auth.username | b64enc | quote }}
  password: {{ printf .Values.mongodb.auth.password | b64enc | quote }}